use_frameworks!

platform :ios, '8.0'

target 'ReactiveDataBoard_Example' do
  pod 'ReactiveDataBoard', :path => '../'

  target 'ReactiveDataBoard_Tests' do
    inherit! :search_paths

    
  end
end
